testing changes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,31 +10,29 @@ on:
 
 jobs:
   test:
-    runs-on: ubuntu-latest
-    steps:
-          - name: Checkout code
-            uses: actions/checkout@v2
+      runs-on: ubuntu-latest
+      steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 11 for x64
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          architecture: x64
 
-          - name: Set up Java
-            uses: actions/setup-java@v2
-            with:
-              java-version: '11'
-              distribution: 'adopt'
-              maven-version: '3.8.x'
+      - name: Run tests
+        run: |
+          ./mvn test jacoco:report
+        working-directory: .
 
-          - name: Run tests
-            run: |
-              ./mvn test jacoco:report
-            working-directory: .
-
-          - name: Check Test Results
-            run: |
-              if [ $? -eq 0 ]; then
-                echo "Tests passed successfully."
-              else
-                echo "Tests failed."
-                exit 1  # Exit with an error code to stop the workflow
-              fi
+      - name: Check Test Results
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Tests passed successfully."
+          else
+            echo "Tests failed."
+            exit 1  # Exit with an error code to stop the workflow
+          fi
 #  build-jar:
 #    runs-on: ubuntu-latest
 #
