testing changes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,81 +9,105 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-jar:
+  test:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+          - name: Checkout code
+            uses: actions/checkout@v2
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
-        with:
-          java-version: '11'
-          distribution: 'adopt'
+          - name: Set up Java
+            uses: actions/setup-java@v2
+            with:
+              java-version: '11'
 
-      - name: Build with Maven
-        run: mvn clean install -DskipTests
+          - name: Run tests
+            run: |
+              ./mvn test jacoco:report
+            working-directory: .
 
-      - name: Install XML parsing tools
-        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
-
-      - name: Extract version from pom.xml
-        run: |
-          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" $GITHUB_WORKSPACE/pom.xml)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-
-      - name: Append version to DEBIAN/control
-        run: |
-          echo "Version: ${{ env.VERSION }}" >> $GITHUB_WORKSPACE/linux-deployment/DEBIAN/control
-          
-      - name: Set execute permissions for postinst script
-        run: chmod 755 $GITHUB_WORKSPACE/linux-deployment/DEBIAN/postinst
-
-      - name: Copy geoweaver.jar to linux-deployment directory
-        run: cp $GITHUB_WORKSPACE/target/geoweaver.jar $GITHUB_WORKSPACE/linux-deployment/usr/local/bin/
-
-      - name: Make geoweaver.sh executable
-        run: chmod +x $GITHUB_WORKSPACE/linux-deployment/usr/local/bin/geoweaver.sh
-
-      # - name: Build deb package
-      #   run: |
-      #     cd $GITHUB_WORKSPACE/linux-deployment
-      #     dpkg-deb --build . geoweaver.deb
-
-      - name: Upload Geoweaver Artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: geoweaver-artifacts
-          path: |
-            target/*.jar
-            pom.xml
-          # linux-deployment/*.deb
+          - name: Check Test Results
+            run: |
+              if [ $? -eq 0 ]; then
+                echo "Tests passed successfully."
+              else
+                echo "Tests failed."
+                exit 1  # Exit with an error code to stop the workflow
+              fi
+#  build-jar:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v2
+#        with:
+#          java-version: '11'
+#          distribution: 'adopt'
+#
+#      - name: Build with Maven
+#        run: mvn clean install -DskipTests
+#
+#      - name: Install XML parsing tools
+#        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
+#
+#      - name: Extract version from pom.xml
+#        run: |
+#          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" $GITHUB_WORKSPACE/pom.xml)
+#          echo "VERSION=$VERSION" >> $GITHUB_ENV
+#
+#      - name: Append version to DEBIAN/control
+#        run: |
+#          echo "Version: ${{ env.VERSION }}" >> $GITHUB_WORKSPACE/linux-deployment/DEBIAN/control
+#
+#      - name: Set execute permissions for postinst script
+#        run: chmod 755 $GITHUB_WORKSPACE/linux-deployment/DEBIAN/postinst
+#
+#      - name: Copy geoweaver.jar to linux-deployment directory
+#        run: cp $GITHUB_WORKSPACE/target/geoweaver.jar $GITHUB_WORKSPACE/linux-deployment/usr/local/bin/
+#
+#      - name: Make geoweaver.sh executable
+#        run: chmod +x $GITHUB_WORKSPACE/linux-deployment/usr/local/bin/geoweaver.sh
+#
+#      # - name: Build deb package
+#      #   run: |
+#      #     cd $GITHUB_WORKSPACE/linux-deployment
+#      #     dpkg-deb --build . geoweaver.deb
+#
+#      - name: Upload Geoweaver Artifacts
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: geoweaver-artifacts
+#          path: |
+#            target/*.jar
+#            pom.xml
+#          # linux-deployment/*.deb
 
   build-windows:
       needs: build-jar
       runs-on: windows-latest
-  
+
       steps:
         - name: Checkout code
           uses: actions/checkout@v2
-  
+
         - name: Download Geoweaver Artifacts
           uses: actions/download-artifact@v2
           with:
             name: geoweaver-artifacts
             path: artifact
-  
+
         - name: Prepare Deployment Directory
           run: |
             cp artifact/target/geoweaver.jar windows-deployment/geoweaver.jar
-  
+
         - name: Install NSIS
           run: choco install nsis
-  
+
         - name: Install PyInstaller
           run: pip install pyinstaller
-  
+
         - name: Build Executable with PyInstaller
           run: pyinstaller windows-deployment/pyinstaller.spec
 
@@ -93,16 +117,16 @@ jobs:
             cd D:\a\geoweaver-deployment-test\geoweaver-deployment-test\dist && ls
             cd D:\a\geoweaver-deployment-test\ && ls
             cd D:\a\geoweaver-deployment-test\geoweaver-deployment-test\dist\geoweaver && ls
-  
+
         - name: Build NSIS Installer
           run: '& "C:\Program Files (x86)\NSIS\makensis.exe" windows-deployment/installer.nsi'
-  
+
         - name: Upload Windows Installer to Release
           uses: actions/upload-artifact@v2
           with:
             name: geoweaver-windows-installer
             path: D:\a\geoweaver-deployment-test\geoweaver-deployment-test\windows-deployment\GeoweaverInstaller.exe
-  
+
   build-macos:
     needs: build-jar
     runs-on: macos-latest
@@ -140,7 +164,7 @@ jobs:
     #     with:
     #       name: geoweaver-dmg
     #       path: /Users/runner/work/geoweaver-deployment-test/geoweaver-deployment-test/Geoweaver.dmg
-  
+
   release:
     needs: [build-jar, build-macos, build-windows]
     runs-on: ubuntu-latest
@@ -156,7 +180,7 @@ jobs:
         uses: actions/download-artifact@v2
         with:
           name: geoweaver-artifacts
-          
+
       - name: Download Windows Installer Artifact
         uses: actions/download-artifact@v2
         with:
@@ -222,4 +246,4 @@ jobs:
       #     asset_content_type: application/x-diskcopy
       #   env:
       #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  
+
